CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    citationId text TEXT NOT NULL,
    authors TEXT,
    publicationDate TEXT,
    abstract TEXT,
    link TEXT UNIQUE,
    keywords TEXT,
    citedBy INT,
    createdAt TIMESTAMPTZ DEFAULT NOW()
);